### ISSUE TITLE
Missing borders on MessageBox and UserPrompt in SampleBrowser

### ISSUE THREAD

**Issue by mgnslndh** [Actipro/Avalonia-Controls#1]
When I run the MessageBox and UserPrompt samples in the SampleBrowser they look OK in the preview but when I open them as real dialogs they are missing the border.

1. Clone the repo
2. Open SampleBrowser.Desktop.sln
3. Build and run SampleBrowser.Desktop 
4. Select Evaluation
5. Navigate to Fundamentals and then MessageBox
6. Click Show MessageBox

![image](https://github.com/Actipro/Avalonia-Controls/assets/1139118/427896f7-e79e-49f5-a4ea-e35508093d38)

OS: Windows 11

PS. Excellent job on releasing the first commerical library for Avalonia. Really looking forward to what is coming next!

**Comment by mgnslndh** [comment]
SampleBrowser.Web works fine:

![image](https://github.com/Actipro/Avalonia-Controls/assets/1139118/43892e4c-a3be-4e31-998b-4a0ff2460a6c)

**Comment by boydpatterson** [comment]
Thank you for sharing this, but I'm not able to reproduce what you show on desktop. I used a clean environment (Windows Sandbox) with fresh install of Visual Studio 2022, cloned our public repo, ran the desktop samples, and I see borders/shadow on prompts opened as a dialog.  On the web, the prompts are shown as an overlay where we render the shadow. On desktop, that's actually the OS shadow for a modal window. No idea why the borders would be missing, though.

Any chance your OS settings have turned off window shadows?

Another thing to try would be running outside the debugger to see if that makes a difference.

**Comment by mgnslndh** [comment]
I tried running outside the debugger and also from inside the sandbox. Same issue.

Oh and I'm sorry, I reported the wrong OS, it should be Windows 10.

Edition:	Windows 10 Pro
Version:	22H2
Installed on:	‎2020-‎12-‎10
OS build:	19045.3448
Experience:	Windows Feature Experience Pack 1000.19044.1000.0

If this is the setting you are referring to it should be on:
![image](https://github.com/Actipro/Avalonia-Controls/assets/1139118/640bda79-df36-430a-a116-946baac14b07)

But, when I DO run it on Windows 11 it works, so I guess its an issue with Windows 10 or a setting in my environment.

![image](https://github.com/Actipro/Avalonia-Controls/assets/1139118/170e0d8e-e362-449b-85c6-5a37e12c5f10)

**Comment by billhenn** [comment]
Thanks for the update.  I can see the same issue on Windows 10, whereas it works on Windows 11.  It seems to be due to our `ChromedTitleBar` control (used in `UserPrompt` in this scenario) setting `Window.ExtendClientAreaToDecorationsHint = true`, along with another related property.  In Windows 10, this appears to cause the `Window` to not render a border, whereas it does in Windows 11.

We are going to talk to the Avalonia team about this since it needs to be consistent one way or the other, and then we'll have to update our appearance accordingly based on what they can do to help in their Win32 interop code.

**Comment by maxkatz6** [comment]
Looks like it's related to this issue https://github.com/AvaloniaUI/Avalonia/issues/9989

**Comment by billhenn** [comment]
I believe we have a workaround for this we are putting in for Windows 10 for the next maintenance release.
