### ISSUE TITLE
String Resource Browser not showing Fundamentals strings

### ISSUE THREAD

**Issue by D0ctorWh0** [Actipro/Avalonia-Controls#11]
After last update of actipro components resource strings from paid components appeared, but they are not displayed in Samples app String Resource Browser because of this line commented out

https://github.com/Actipro/Avalonia-Controls/blob/87316b5240033fc667eea798a3e6e3c049b2e157/Samples/SampleBrowser/SampleBrowser.Common/SampleBrowser/Utilities/StringResourceBrowser/StringResourceBrowserViewModel.cs#L37C6-L37C102

**Comment by billhenn** [comment]
Thanks for reporting this.  Fundamentals didn't originally have any string resources, so we had left it out.  It does have several as of the recent builds.  We updated the code just now to include the Fundamentals library in the dropdown.
