### ISSUE TITLE
Thank you ❤

### ISSUE THREAD

**Issue by 0x90d** [Actipro/Avalonia-Controls#2]
I just want to say thank you so much for offering a professional Avalonia theme for free. I can only imagine how much work you put into this. Especially that DataGrid theme is part of it. This is exactly what I've been looking for my open source project. The integration was easy and I haven't encountered any problems.

**Comment by billhenn** [comment]
We appreciate the comments.  Yes, it has been a lot of time and effort, but we want to do our part to help the Avalonia community grow.  We are excited to see our controls and themes used in open-source projects like yours.
