### ISSUE TITLE
Material Icons Support?

### ISSUE THREAD

**Issue by Touseefelahi** [Actipro/Avalonia-Controls#3]
Hi,
Thanks for this wonderful theme library.
I wanted to know if there is a way to use Material icons (https://www.nuget.org/packages/Material.Icons.Avalonia) with the actipro controls?

I am trying to use the material icons, but they are not rendering at all.

**Comment by boydpatterson** [comment]
I just tried using a material icon as the content of a button with our native themes enabled, and the icon rendered as expected. 
 Can you please provide additional information about what you are trying? Some sample code would really help clarify.

Are the icons working in other parts of the application, but not with Actipro controls? If only Actipro controls, which controls and which properties on those controls are you trying to set to the icon on?  Please note that some of our controls have properties that expect an `IImage`, and a material icon is not an `IImage`. We hope to open up those controls in a future release to allow much customization around images.

**Comment by Touseefelahi** [comment]
I am using like this in the provided actripro sample 'SampleBrowser.Desktop' and it is not rendering the icon. I am not sure what I am doing wrong.

     xmlns:icon="clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia"

             <Button
                   Grid.Row="3"
                   Grid.Column="9"
                   IsEnabled="False">
                   <icon:MaterialIcon
                       Width="25"
                       Height="25"
                       HorizontalAlignment="Center"
                       BorderThickness="0"
                       Foreground="Black"
                       Kind="TrayDownload" />
               </Button>
               


![image](https://github.com/Actipro/Avalonia-Controls/assets/20659468/372eb249-cab0-496d-b2cf-e907af8b044e)

**Comment by Touseefelahi** [comment]
The icons are not working at all, not even as a separate icon.
They were working before when I was not using Actipro, this is why I thought it is related to the theme. Can you provide me the code that you used to test?

**Comment by billhenn** [comment]
Hello, I believe you forgot to include the code required in `Application.Styles` that initializes that library as described in their [GitHub repo readme](https://github.com/SKProCH/Material.Icons).  Since `MaterialIcon` is a `TemplatedControl`, if you don't include that app initialization logic, it will appear blank.  When I added that, I could see the icon fine in our sample.

**Comment by Touseefelahi** [comment]
Thanks you very much!
