### ISSUE TITLE
Virtual Keyboard Control

### ISSUE THREAD

**Issue by mozesa** [Actipro/Avalonia-Controls#4]
Dear **Actipro**,

First, I would like to express my sincere gratitude for _Actipro Avalonia UI Products_.

I would like to suggest you to implement a Virtual Keyboard Control.

AFAIK (currently) Avalonia UI doesn't have Virtual Keyboard Control and not support Windows' native OSK API.

At the company working for, we have a lot of terminals, which hopefully soon will run an Avalonia UI based app.
Actipro's Virtual Keyboard Control instead of physical keyboards would save a lot both in money (as physical keyboards are worn out frequently) and time.

BR!

**Comment by billhenn** [comment]
Thank you for the suggestion.  We've written it down on our end and will reopen this issue if work begins on it in the future.
