### ISSUE TITLE
How to use AOT with NativeDataGrid

### ISSUE THREAD

**Issue by Touseefelahi** [Actipro/Avalonia-Controls#6]
If I am using NativeDataGrid `<actipro:ModernTheme Includes="NativeDataGrid" />`  in my application, the application does not work in AOT mode.

This is the error that I get
Avalonia.Markup.Xaml.XamlLoadException: 'No precompiled XAML found for avares://ActiproSoftware.Avalonia.Themes.Native.DataGrid/Themes/Common.axaml (baseUri: ), make sure to specify x:Class and include your XAML file as AvaloniaResource'

I tried with Fluent Theme it works since I am using the style like this:

```
<Application.Resources>
	<StyleInclude x:Key="fluentDataGrid" Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml" />
	<StyleInclude x:Key="simpleDataGrid" Source="avares://Avalonia.Controls.DataGrid/Themes/Simple.xaml" />
</Application.Resources>

```

I am missing something or there any solution?
Thank you

**Comment by Touseefelahi** [comment]
I am using the latest version

**Comment by boydpatterson** [comment]
We are still researching what is necessary to best ensure our assemblies properly support trimming without requiring workarounds.  For now, though, could you try adding the following just like you're doing for the fluent theme?

```
<StyleInclude Source="avares://ActiproSoftware.Avalonia.Themes.Native.DataGrid/Themes/Common.axaml" />
```

That should make sure the styles are referenced from your app and prevent them from being trimmed.

**Comment by Touseefelahi** [comment]
It worked, thank you for your support

**Comment by boydpatterson** [comment]
Great! We are working on updates in the next release to mark those theme resources as being dynamically referenced by our `ModernTheme` so they won't get trimmed. Until then, the explicit reference will make sure they don't get trimmed.
