### ISSUE TITLE
Version description / "list of changes" is missing

### ISSUE THREAD

**Issue by Touseefelahi** [Actipro/Avalonia-Controls#8]
I don't know how to reach you out this is why just creating this issue. Firstly, Thank you for the new release, I really appreciate it.

I just wanted to mention that version description in release will be really appreciated. Currently, it is not clear what to expect from the new version.

**Comment by billhenn** [comment]
Hello, we're happy you are enjoying the release.  Thank you for the suggestion.  We already had the Release History within our samples app via Markdown documents in [this folder](https://github.com/Actipro/Avalonia-Controls/blob/develop/Samples/SampleBrowser/SampleBrowser.Common/SampleBrowser/Documents/ReleaseHistories) but that is admittedly not as straightforward to find as also putting the information in the GitHub release notes.  We've updated the GitHub release notes with the same information and will do so moving forward.
